---
title: 'Project 2: Modeling, Testing, and Predicting'
author: "SDS348"
date: ''
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
---

```{r setup, include=FALSE}
library(knitr)
hook_output = knit_hooks$get('output')
knit_hooks$set(output = function(x, options) {
  # this hook is used only when the linewidth option is not NULL
  if (!is.null(n <- options$linewidth)) {
    x = knitr:::split_lines(x)
    # any lines wider than n should be wrapped
    if (any(nchar(x) > n)) x = strwrap(x, width = n)
    x = paste(x, collapse = '\n')
  }
  hook_output(x, options)
})

knitr::opts_chunk$set(echo = TRUE, eval = TRUE,fig.align="center",warning=FALSE,message=FALSE,fig.width=8, fig.height=5, linewidth=60)
options(tibble.width = 100,width = 100)
library(tidyverse)
```

# Modeling

## Instructions

A knitted R Markdown document (preferably HTML) and the raw R Markdown file (as .Rmd) should both be submitted to Canvas by 11:59pm on the due date. These two documents will be graded jointly, so they must be consistent (i.e., don’t change the R Markdown file without also updating the knitted document). In the .Rmd file for Project 2, you can copy the first code-chunk into your project .Rmd file to get better formatting. Notice that you can adjust the opts_chunk$set(...) above to set certain parameters if necessary to make the knitting cleaner (you can globally set the size of all plots, etc). You can copy the set-up chunk in Project2.Rmd: I have gone ahead and set a few for you (such as disabling warnings and package-loading messges when knitting)! 

Like before, I envision your written text forming something of a narrative structure around your code/output. All results presented must have corresponding code. Any answers/results/plots etc. given without the corresponding R code that generated the result will not be graded. Furthermore, all code contained in our project document should work properly. Please do not include any extraneous code or code which produces error messages. (Code which produces warnings is fine as long as you understand what the warnings mean.)

## Find data:

Find one dataset with at least 5 variables (ideally more!) that you want to use to build models/test hypotheses. At least one should be categorical (with 2-5 groups, ideally; definitely fewer than 10) and at least two should be numeric (taking on more than 10 distinct values). Ideally, at least of your variables will be binary (if not, you will have to create one by discretizing a numeric or collapsing levels of a categorical). You will need a minimum of 40 observations (*at least* 10 observations for every explanatory variable you have, ideally 20+ observations/variable).

It is perfectly fine to use either dataset (or the merged dataset, or a subset of your variables) from Project 1. However, I might encourage you to diversify things a bit and choose a different dataset to work with (particularly if the variables did not reveal interesting associations in Project 1 that you want to follow up with). The only requirement/restriction is that you may not use data from any examples we have done in class or lab. It would be a good idea to pick more cohesive data this time around (i.e., variables that you actually thing might have a relationship you would want to test). Think more along the lines of your Biostats project.

Again, you can use data from anywhere you want (see bottom for resources)! If you want a quick way to see whether a built-in (R) dataset has binary and/or character (i.e., categorical) variables, check out this list: https://vincentarelbundock.github.io/Rdatasets/datasets.html.


## Guidelines and Rubric

- **0. (5 pts)** Introduce your dataset and each of your variables (or just your main variables if you have lots) in a paragraph. What are they measuring? How many observations?
```{R}
clinical<- read.table("ccle_broad_2019_clinical_data.tsv",header=T, sep="\t")
mRNA <- read.table("mRNA.txt",header=T, sep="\t")
combine <- left_join(clinical, mRNA, by=c("Sample_ID"="SAMPLE_ID")) %>% unite("Tumor_Sample_Type", Tumor_Type:Sample_Type, na.rm = TRUE, remove = FALSE) %>% na.omit()
glimpse(combine)
```
In this project, I will use the same dataset as project, since I have found interesting correlation between H2AFX in breast cancer. I found H2AFX has a higher expression in metastasis breast cancer compare to primary breast cancer. Therefore, I would like to explore more about this dataset with difference in metastasis and primary in both breast and colorectal cancer.

- **1. (15 pts)** Perform a MANOVA testing whether any of your numeric variables (or a subset of them, if including them all is unreasonable or doesn't make sense) show a mean difference across levels of one of your categorical variables (3). If they do, perform univariate ANOVAs to find response(s) showing a mean difference across groups (3), and perform post-hoc t tests to find which groups differ (3). Discuss the number of tests you have performed, calculate the probability of at least one type I error (if unadjusted), and adjust the significance level accordingly (bonferroni correction) before discussing significant differences (3). Briefly discuss some of the MANOVA assumptions and whether or not they are likely to have been met here (no need for anything too in-depth) (2).
```{R}
###MANOVA
man1<-manova(cbind(Age,Genome_Altered,Mutation_Count,HK2,KEAP1,H2AFX,TP63)~Tumor_Sample_Type, data=combine) 
summary(man1)
###univariate ANOVAs
summary.aov(man1) 
###post-hoc t 
combine%>%group_by(Tumor_Sample_Type)%>%summarize(mean(H2AFX),mean(Genome_Altered),mean(Mutation_Count))
pairwise.t.test(combine$H2AFX, combine$Tumor_Sample_Type, p.adj="none")
pairwise.t.test(combine$Genome_Altered, combine$Tumor_Sample_Type, p.adj="none")
pairwise.t.test(combine$Mutation_Count, combine$Tumor_Sample_Type, p.adj="none")
```

The overall MANOVA is significant (p=0.00293), then I did a one-way ANOVAs for each variable, and found Genome_Altered , Mutation_Count and H2AFX are significant. 

I have done 1 MANOVA and 7 anovas,and 18 (3 different variables in 4 groups) t-test, total 26 tests. The type I error rate is .05/26=0.001923077. Based on this value, expression level of H2AFX for primary site is significant between colorectal and breast cancer. Genome_Altered is significant for primary sites, metastasis and primary sites between colorectal and breast cancer. Mutation_Count for primary site is significant between colorectal and breast cancer, and is also significant between colorectal_Primary vs. breast_Metastasis.

Since breast cancer and colorectal cancer are different cancer type, their genomic alteration might also be different. And I also found Genome_Altered and Mutation_Count are significant different for primary sites between colorectal and breast cancer. 

- **2. (10 pts)** Perform some kind of randomization test on your data (that makes sense). The statistic can be anything you want (mean difference, correlation, F-statistic/ANOVA, chi-squared), etc. State null and alternative hypotheses, perform the test, and interpret the results (7). Create a plot visualizing the null distribution and the test statistic (3).
```{R}
combine_2 <- left_join(clinical, mRNA, by=c("Sample_ID"="SAMPLE_ID")) %>% filter(Tumor_Type=="breast") %>% na.omit() %>% select(Sample_Type, H2AFX)
combine_2 %>% group_by(Sample_Type) %>% summarise(means=mean(H2AFX)) %>% summarise(diff(means))
rand_dist<-vector()
for(i in 1:5000){ 
  new<-data.frame(Sample_Type=sample(combine_2$Sample_Type),H2AFX=combine_2$H2AFX) 
  rand_dist[i]<-mean(new[new$Sample_Type=="Primary",]$H2AFX)-
  mean(new[new$Sample_Type=="Metastasis",]$H2AFX)}
mean(rand_dist>0.5737567 | rand_dist < -0.5737567)
hist(rand_dist,main="",ylab="")
abline(v = c(-0.5737567, 0.5737567),col="red")
```
My project will mainly focus on the function of DNA damage response gene H2AFX in breast cancer primary sites and breast cancer metastasis sites. So I selected breast cancer and H2AFX expression level to explore if it is significant between primary and metastasis sites in breast cancer. My null hypothesis is there is no difference between primary and metastasis sites. I performed 5000 times randomization of my data and explored distribution. I found the p-value is 0.036, then I rejected the null hypothesis.


- **3. (40 pts)** Build a linear regression model predicting one of your response variables from at least 2 other variables, including their interaction. Mean-center any numeric variables involved in the interaction.

    - Interpret the coefficient estimates (do not discuss significance) (10)
    - Plot the regression using `ggplot()` using geom_smooth(method="lm"). If your interaction is numeric by numeric, refer to code in the slides to make the plot or check out the `interactions` package, which makes this easier. If you have 3 or more predictors, just chose two of them to plot for convenience. (10)
    - What proportion of the variation in the outcome does your model explain? (4)
    - Check assumptions of linearity, normality, and homoskedasticity either graphically or using a hypothesis test (5)
    - Regardless, recompute regression results with robust standard errors via `coeftest(..., vcov=vcovHC(...))`. Discuss significance of results, including any changes from before/after robust SEs if applicable. (10)
```{R}
library(lmtest)
library(sandwich)
combine_3 <- left_join(clinical, mRNA, by=c("Sample_ID"="SAMPLE_ID")) %>% filter(Tumor_Type=="colorectal") %>% na.omit() 
combine_3_c <- combine_3 %>% mutate(Genome_Altered_c=Genome_Altered-mean(Genome_Altered)) %>% mutate(Mutation_Count_c=Mutation_Count-mean(Mutation_Count)) %>% mutate(H2AFX_c=H2AFX-mean(H2AFX))
#combine_3_c$Sample_Type<-relevel(combine_3_c$Sample_Type,ref="Primary")
fit<-lm(Genome_Altered_c ~ Mutation_Count_c*Sample_Type, data=combine_3_c); summary(fit)
combine_3_c %>% ggplot(aes(Genome_Altered_c,Mutation_Count_c,group=Sample_Type)) + geom_point(aes(color=Sample_Type)) +geom_smooth(aes(color=Sample_Type),method="lm")
###Check assumptions of linearity, normality, and homoskedasticity either graphically or using a hypothesis test 
resids<-fit$residuals
fitvals<-fit$fitted.values
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, color='red')
ks.test(resids, "pnorm", mean=0, sd(resids))
shapiro.test(resids)
coeftest(fit)
coeftest(fit, vcov=vcovHC(fit))
```

I tried to explore relationship among all the variables with Genome_Altered in colorectal cancer. Mean/predicted Genome_Altered_c for primary site with average Mutation_Count is 3.665e-03. Mutation_Count significantly associated with Genome_Altered_c for primary site: for every 1-unit increase in Mutation_Count, predicted Genome_Altered_c decreased 3.983e-05 for this group. Metastasis with average Mutation_Count have predicted Genome_Altered_c that is 1.689e-01 lower than primary sites with average Mutation_Count. Slope of Mutation_Count on Genome_Altered_c for Metastasis is 1.361e-04 lower than primary sites.

The R-square is 0.3453, so my model could explain 34.53% of the variation in the outcome.

With both Kolmogorov-Smirnov and Shapiro-Wilk, I failed to reject, hence the normality is fine.

With the robust standard errors, Metastasis with average Mutation_Count have predicted Genome_Altered_c that is 1.6894e-01 lower than primary sites with average Mutation_Count(significant). Slope of Mutation_Count on Genome_Altered_c for Metastasis is 1.3609e-04 lower than primary sites (significant). However, Mutation_Count is not significantly associated with Genome_Altered_c for primary site.

- **4. (5 pts)** Rerun same regression model (with the interaction), but this time compute bootstrapped standard errors (either by resampling observations or residuals). Discuss any changes you observe in SEs and p-values using these SEs compared to the original SEs and the robust SEs)
```{R}
combine_4 <- combine_3_c %>% select(Genome_Altered_c, Mutation_Count_c, Sample_Type)
samp_distn<-replicate(5000, { 
  combine_4_p <- combine_4[combine_4$Sample_Type=="Primary",]
  combine_4_m <- combine_4[combine_4$Sample_Type=="Metastasis",]
  boot_dat_p<-combine_4_p[sample(nrow(combine_4_p),replace=TRUE),] 
  boot_dat_m<-combine_4_m[sample(nrow(combine_4_m),replace=TRUE),] 
  boot_dat <- merge(boot_dat_p,boot_dat_m, all=T)
  fit<-lm(Genome_Altered_c ~ Mutation_Count_c*Sample_Type, data=boot_dat)
coef(fit)
})
samp_distn%>%t%>%as.data.frame%>%summarize_all(sd)
samp_distn%>%t%>%as.data.frame%>%gather%>%group_by(key)%>% summarize(lower=quantile(value,.025), upper=quantile(value,.975))

```
With bootstrapped standard errors, none of my variables is significant. Since the standard errors are too big for them to be significant.

- **5. (30 pts)** Fit a logistic regression model predicting a binary variable (if you don't have one, make/get one) from at least two explanatory variables (interaction not necessary). 

    - Interpret coefficient estimates in context (10)
    - Report a confusion matrix for your logistic regression (5)
    - Compute and discuss the Accuracy, Sensitivity (TPR), Specificity (TNR), Precision (PPV), and AUC of your model (5)
    - Using ggplot, make a density plot of the log-odds (logit) colored/grouped by your binary outcome variable (5)
    - Generate an ROC curve (plot) and calculate AUC (either manually or with a package); interpret (5)
```{R}
combine_5 <- left_join(clinical, mRNA, by=c("Sample_ID"="SAMPLE_ID")) %>% filter(Tumor_Type=="breast") %>% na.omit()
data<-combine_5 %>%mutate(y=ifelse(Sample_Type=="Metastasis",1,0))
fit<-glm(y~H2AFX+Mutation_Count+Genome_Altered,data=data,family="binomial")
coeftest(fit)
exp(coef(fit))
data$predicted <- predict(fit, type = "response")
table(predict=as.numeric(data$predicted>.5),truth=data$y)%>%addmargins
#sensitivity
mean(data[data$y==1,]$predicted>.5)
#specificity
mean(data[data$y==0,]$predicted<.5)
#Precision
18/27
data$logit<-predict(fit,  type= "link")
ggplot(data, aes(x=logit,fill=Sample_Type))+geom_density(alpha = 0.5)
library(plotROC)
ROCplot<-ggplot(data)+geom_roc(aes(d=y,m=predicted), n.cuts=0); ROCplot
calc_auc(ROCplot)
```
For breast cancer, log-odds for primary site is 2.66351038, odds is 14.34656265.  Log-odds for metastasis site is 2.66351038+0.65645350-0.00032663-3.87198441=-0.5523472, odds is 0.5755972.

Sensitivity is 0.6923077, specificity is 0.625 and precision is 0.6666667. The AUC is 0.7323718.



- **6. (25 pts)** Perform a logistic regression predicting the same binary response variable from *ALL* of the rest of your variables (the more, the better!) 

    - Fit model, compute in-sample classification diagnostics (Accuracy, Sensitivity, Specificity, Precision, AUC), and interpret (5)
    - Perform 10-fold (or repeated random sub-sampling) CV with the same model and report average out-of-sample classification diagnostics (Accuracy, Sensitivity, Specificity, Precision, and AUC); interpret AUC and compare with the in-sample metrics (10)
    - Perform LASSO on the same model/variables. Choose lambda to give the simplest model whose accuracy is near that of the best (i.e., `lambda.1se`). Discuss which variables are retained. (5)
    - Perform 10-fold CV using only the variables lasso selected: compare model's out-of-sample AUC to that of your logistic regressions above (5)
```{R}
class_diag<-function(probs,truth){
  
  tab<-table(factor(probs>.5,levels=c("FALSE","TRUE")),truth)
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2]
  spec=tab[1,1]/colSums(tab)[1]
  ppv=tab[2,2]/rowSums(tab)[2]
  
  if(is.numeric(truth)==FALSE & is.logical(truth)==FALSE) truth<-as.numeric(truth)-1
  
  #CALCULATE EXACT AUC
  ord<-order(probs, decreasing=TRUE)
  probs <- probs[ord]; truth <- truth[ord]
  
  TPR=cumsum(truth)/max(1,sum(truth)) 
  FPR=cumsum(!truth)/max(1,sum(!truth))
  
  dup<-c(probs[-1]>=probs[-length(probs)], FALSE)
  TPR<-c(0,TPR[!dup],1); FPR<-c(0,FPR[!dup],1)
  
  n <- length(TPR)
  auc<- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )
  
  data.frame(acc,sens,spec,ppv,auc)
}


combine_6 <- left_join(clinical, mRNA, by=c("Sample_ID"="SAMPLE_ID")) %>% filter(Tumor_Type=="breast") %>% na.omit()
data6<-combine_6 %>%mutate(y=ifelse(Sample_Type=="Metastasis",1,0))
data_fin<-data6 %>% select(-Sample_ID,-STUDY_ID,-Tumor_Type,-Sample_Type)
fit<-glm(y~.,data=data_fin,family="binomial")
coeftest(fit)
exp(coef(fit))
data_fin$predicted <- predict(fit, type = "response")
table(predict=as.numeric(data_fin$predicted>.5),truth=data_fin$y)%>%addmargins
#sensitivity
mean(data_fin[data_fin$y==1,]$predicted>.5)
#specificity
mean(data_fin[data_fin$y==0,]$predicted<.5)
#Precision
19/27
#Accuracy
(16+19)/50
#AUC
library(plotROC)
ROCplot<-ggplot(data_fin)+geom_roc(aes(d=y,m=predicted), n.cuts=0); ROCplot
calc_auc(ROCplot)
#10-fold 
set.seed(1234)
k=10
data_fold <- data_fin %>% sample_frac
folds <- ntile(1:nrow(data_fold),n=10)
diags<-NULL
for(i in 1:k){
  train <- data_fold[folds!=i,]
  test <- data_fold[folds==i,]
  truth <- test$y
  fit <- glm(y~., data=train, family="binomial")
  probs <- predict(fit, newdata=test, type="response")
  
  diags<-rbind(diags,class_diag(probs,truth))
}
mean(diags$acc)
mean(diags$sens)
mean(diags$spec)
mean(diags$ppv)
mean(diags$auc)

###LASSO
data_lasso<-data6 %>% select(-Sample_ID,-STUDY_ID,-Tumor_Type,-y)
library(glmnet)
y<-as.matrix(data_lasso$Sample_Type)
x<-model.matrix(Sample_Type~.,data=data_lasso)[,-1] 
cv<-cv.glmnet(x,y,family="binomial")
cv<-cv.glmnet(x,y,family="binomial")
plot(cv$glmnet.fit,"lambda",labe=TRUE); abline(v = log(cv$lambda.1se)); abline(v = log(cv$lambda.min),lty=2)
lasso<-glmnet(x,y,family="binomial",lambda=cv$lambda.1se)
coef(lasso)

#10-fold with new 
combine_6 <- left_join(clinical, mRNA, by=c("Sample_ID"="SAMPLE_ID")) %>% filter(Tumor_Type=="breast") %>% na.omit()
data6<-combine_6 %>%mutate(y=ifelse(Sample_Type=="Metastasis",1,0))
set.seed(1234)
k=10
data_fold_lasso <- data6 %>% sample_frac
folds <- ntile(1:nrow(data_fold_lasso),n=10)
diags<-NULL
for(i in 1:k){
  train <- data_fold_lasso[folds!=i,]
  test <- data_fold_lasso[folds==i,]
  truth <- test$y
  fit <- glm(y~Genome_Altered, data=train, family="binomial")
  probs <- predict(fit, newdata=test, type="response")
  
  diags<-rbind(diags,class_diag(probs,truth))
}
mean(diags$auc)
```

Sensitivity is 0.7307692, specificity is 0.6666667 ,precision is 0.7037037 and the accuracy is 0.7. The AUC is 0.7772436.

After 10-fold the sensitivity is 0.6083333, specificity is 0.525 ,precision is 0.5216667 and the accuracy is 0.56. The AUC is 0.5083333. Which indicated my data is overfitting.

With LASSO I will keep Genome_Altered.

With the new variable, my 10-fold auc is 0.6666667.
## Where do I find data again?

You can choose ANY datasets you want that meet the above criteria for variables and observations. You can make it as serious as you want, or not, but keep in mind that you will be incorporating this project into a portfolio webpage for your final in this course, so choose something that really reflects who you are, or something that you feel will advance you in the direction you hope to move career-wise, or something that you think is really neat, or whatever. On the flip side, regardless of what you pick, you will be performing all the same tasks, so it doesn't end up being that big of a deal.

If you are totally clueless and have no direction at all, log into the server and type 

```{R eval=F}
data(package = .packages(all.available = TRUE))
```

This will print out a list of **ALL datasets in ALL packages** installed on the server (a ton)! Scroll until your eyes bleed! Actually, do not scroll that much... To start with something more manageable, just run the command on your own computer, or just run `data()` to bring up the datasets in your current environment. To read more about a dataset, do `?packagename::datasetname`. 

If it is easier for you, and in case you don't have many packages installed, a list of R datasets from a few common packages (also downloadable in CSV format) is given at the following website: https://vincentarelbundock.github.io/Rdatasets/datasets.html.

- A good package to download for fun/relevant data is `fivethiryeight`. 
Run `install.packages("fivethirtyeight"),` load the packages with `library(fivethirtyeight)`, run `data()`, and then scroll down to view the datasets. Here is an online list of all 127 datasets (with links to the 538 articles). Lots of sports, politics, current events, etc.

- If you have already started to specialize (e.g., ecology, epidemiology) you might look at discipline-specific R packages (vegan, epi, respectively). We will be using some tools from these packages later in the course, but they come with lots of data too, which you can explore according to the directions above

- However, you *emphatically DO NOT* have to use datasets available via R packages! In fact, I would much prefer it if you found the data from completely separate sources and brought them together (a much more realistic experience in the real world)! You can even reuse data from your SDS328M project, provided it shares a variable in common with other data which allows you to  merge the two together (e.g., if you still had the timestamp, you could look up the weather that day: https://www.wunderground.com/history/). If you work in a research lab or have access to old data, you could potentially merge it with new data from your lab!

- Here is a curated list of interesting datasets (read-only spreadsheet format): https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit

- Here is another great compilation of datasets: https://github.com/rfordatascience/tidytuesday

- Here is the UCI Machine Learning Repository: https://archive.ics.uci.edu/ml/index.php

    - See also https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data

- Here is another good general place to look: https://www.kaggle.com/datasets

- To help narrow your search down or to see interesting variable ideas, check out https://www.tylervigen.com/spurious-correlations. This is the spurious correlations website, and it is fun, but if you look at the bottom of each plot you will see sources for the data. This is a good place to find very general data (or at least get a sense of where you can scrape data together from)!

- If you are interested in medical data, check out www.countyhealthrankings.org

- If you are interested in scraping UT data, they make *loads* of data public (e.g., beyond just professor CVs and syllabi). Check out all the data that is available in the statistical handbooks: https://reports.utexas.edu/statistical-handbook

##### Broader data sources:

[Data.gov](www.data.gov) 186,000+ datasets!

[Social Explorer](Social Explorer) is a nice interface to Census and American Community Survey data (more user-friendly than the government sites). May need to sign up for a free trial.

[U.S. Bureau of Labor Statistics](www.bls.gov)

[U.S. Census Bureau](www.census.gov)

[Gapminder](www.gapminder.org/data), data about the world.

...





