<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Yue Liu" />
    
    <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico">
    <title>Project 2: Modeling, Testing, and Predicting</title>
    <meta name="generator" content="Hugo 0.83.1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="/post/">BLOG</a></li>
        
        <li><a href="/projects/">PROJECTS</a></li>
        
        <li><a href="/resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="/project/project2/">Project 2: Modeling, Testing, and Predicting</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         January 1, 0001 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="modeling" class="section level1">
<h1>Modeling</h1>
<div id="instructions" class="section level2">
<h2>Instructions</h2>
<p>A knitted R Markdown document (preferably HTML) and the raw R Markdown file (as .Rmd) should both be submitted to Canvas by 11:59pm on the due date. These two documents will be graded jointly, so they must be consistent (i.e., don’t change the R Markdown file without also updating the knitted document). In the .Rmd file for Project 2, you can copy the first code-chunk into your project .Rmd file to get better formatting. Notice that you can adjust the opts_chunk$set(…) above to set certain parameters if necessary to make the knitting cleaner (you can globally set the size of all plots, etc). You can copy the set-up chunk in Project2.Rmd: I have gone ahead and set a few for you (such as disabling warnings and package-loading messges when knitting)!</p>
<p>Like before, I envision your written text forming something of a narrative structure around your code/output. All results presented must have corresponding code. Any answers/results/plots etc. given without the corresponding R code that generated the result will not be graded. Furthermore, all code contained in our project document should work properly. Please do not include any extraneous code or code which produces error messages. (Code which produces warnings is fine as long as you understand what the warnings mean.)</p>
</div>
<div id="find-data" class="section level2">
<h2>Find data:</h2>
<p>Find one dataset with at least 5 variables (ideally more!) that you want to use to build models/test hypotheses. At least one should be categorical (with 2-5 groups, ideally; definitely fewer than 10) and at least two should be numeric (taking on more than 10 distinct values). Ideally, at least of your variables will be binary (if not, you will have to create one by discretizing a numeric or collapsing levels of a categorical). You will need a minimum of 40 observations (<em>at least</em> 10 observations for every explanatory variable you have, ideally 20+ observations/variable).</p>
<p>It is perfectly fine to use either dataset (or the merged dataset, or a subset of your variables) from Project 1. However, I might encourage you to diversify things a bit and choose a different dataset to work with (particularly if the variables did not reveal interesting associations in Project 1 that you want to follow up with). The only requirement/restriction is that you may not use data from any examples we have done in class or lab. It would be a good idea to pick more cohesive data this time around (i.e., variables that you actually thing might have a relationship you would want to test). Think more along the lines of your Biostats project.</p>
<p>Again, you can use data from anywhere you want (see bottom for resources)! If you want a quick way to see whether a built-in (R) dataset has binary and/or character (i.e., categorical) variables, check out this list: <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a>.</p>
</div>
<div id="guidelines-and-rubric" class="section level2">
<h2>Guidelines and Rubric</h2>
<ul>
<li><strong>0. (5 pts)</strong> Introduce your dataset and each of your variables (or just your main variables if you have lots) in a paragraph. What are they measuring? How many observations?</li>
</ul>
<pre class="r"><code>clinical&lt;- read.table(&quot;ccle_broad_2019_clinical_data.tsv&quot;,header=T, sep=&quot;\t&quot;)
mRNA &lt;- read.table(&quot;mRNA.txt&quot;,header=T, sep=&quot;\t&quot;)
combine &lt;- left_join(clinical, mRNA, by=c(&quot;Sample_ID&quot;=&quot;SAMPLE_ID&quot;)) %&gt;% unite(&quot;Tumor_Sample_Type&quot;, Tumor_Type:Sample_Type, na.rm = TRUE, remove = FALSE) %&gt;% na.omit()
glimpse(combine)</code></pre>
<pre><code>## Rows: 90
## Columns: 12
## $ Sample_ID &lt;chr&gt; &quot;AU565_BREAST&quot;, &quot;BT20_BREAST&quot;,
&quot;BT474_BREAST&quot;, &quot;BT483_BREAST&quot;, &quot;BT549_BR…
## $ Age &lt;int&gt; 43, 74, 60, 23, 72, 72, 43, 58, 45, 35, 51,
55, 69, 55, 62, 46, 50, 71, …
## $ Genome_Altered &lt;dbl&gt; 0.7080, 0.9378, 0.6866, 0.6357,
0.5853, 0.4110, 0.5480, 0.2155, 0.0330, …
## $ Mutation_Count &lt;int&gt; 559, 416, 1025, 531, 200, 319,
181, 577, 824, 216, 455, 324, 395, 8244, …
## $ Tumor_Sample_Type &lt;chr&gt; &quot;breast_Metastasis&quot;,
&quot;breast_Primary&quot;, &quot;breast_Primary&quot;, &quot;breast_Primary…
## $ Sample_Type &lt;chr&gt; &quot;Metastasis&quot;, &quot;Primary&quot;, &quot;Primary&quot;,
&quot;Primary&quot;, &quot;Primary&quot;, &quot;Primary&quot;, &quot;Me…
## $ Tumor_Type &lt;chr&gt; &quot;breast&quot;, &quot;breast&quot;, &quot;breast&quot;,
&quot;breast&quot;, &quot;breast&quot;, &quot;colorectal&quot;, &quot;breast&quot;…
## $ STUDY_ID &lt;chr&gt; &quot;ccle_broad_2019&quot;, &quot;ccle_broad_2019&quot;,
&quot;ccle_broad_2019&quot;, &quot;ccle_broad_201…
## $ HK2 &lt;dbl&gt; 1.4764, -0.7664, 0.5178, 0.5654, 0.7627,
0.1286, 0.4232, 0.2388, -1.3032…
## $ KEAP1 &lt;dbl&gt; -2.8521, -0.4570, 0.3060, -2.1686, 0.2310,
-0.0885, -0.2591, 0.7132, -0.…
## $ H2AFX &lt;dbl&gt; -0.3328, 0.9800, 0.1965, -0.7191, -0.0647,
0.9853, 0.1485, 1.0397, 0.814…
## $ TP63 &lt;dbl&gt; -0.4770, -0.0948, -0.1020, -0.4946,
-0.3974, -0.5109, -0.5381, -0.4814, …</code></pre>
<p>In this project, I will use the same dataset as project, since I have found interesting correlation between H2AFX in breast cancer. I found H2AFX has a higher expression in metastasis breast cancer compare to primary breast cancer. Therefore, I would like to explore more about this dataset with difference in metastasis and primary in both breast and colorectal cancer.</p>
<ul>
<li><strong>1. (15 pts)</strong> Perform a MANOVA testing whether any of your numeric variables (or a subset of them, if including them all is unreasonable or doesn’t make sense) show a mean difference across levels of one of your categorical variables (3). If they do, perform univariate ANOVAs to find response(s) showing a mean difference across groups (3), and perform post-hoc t tests to find which groups differ (3). Discuss the number of tests you have performed, calculate the probability of at least one type I error (if unadjusted), and adjust the significance level accordingly (bonferroni correction) before discussing significant differences (3). Briefly discuss some of the MANOVA assumptions and whether or not they are likely to have been met here (no need for anything too in-depth) (2).</li>
</ul>
<pre class="r"><code>###MANOVA
man1&lt;-manova(cbind(Age,Genome_Altered,Mutation_Count,HK2,KEAP1,H2AFX,TP63)~Tumor_Sample_Type, data=combine) 
summary(man1)</code></pre>
<pre><code>## Df Pillai approx F num Df den Df Pr(&gt;F)
## Tumor_Sample_Type 3 0.46741 2.162 21 246 0.00293 **
## Residuals 86
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>###univariate ANOVAs
summary.aov(man1) </code></pre>
<pre><code>## Response Age :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Tumor_Sample_Type 3 1234.6 411.54 2.4285 0.07084 .
## Residuals 86 14573.9 169.46
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response Genome_Altered :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Tumor_Sample_Type 3 1.2113 0.40378 8.7504 3.963e-05 ***
## Residuals 86 3.9684 0.04614
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response Mutation_Count :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Tumor_Sample_Type 3 67599409 22533136 4.1791 0.008212 **
## Residuals 86 463698893 5391848
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response HK2 :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Tumor_Sample_Type 3 0.418 0.13937 0.1385 0.9367
## Residuals 86 86.523 1.00608
##
## Response KEAP1 :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Tumor_Sample_Type 3 4.745 1.58166 1.6955 0.174
## Residuals 86 80.226 0.93286
##
## Response H2AFX :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Tumor_Sample_Type 3 6.473 2.15767 2.9077 0.0392 *
## Residuals 86 63.816 0.74205
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response TP63 :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Tumor_Sample_Type 3 0.747 0.24886 0.645 0.5882
## Residuals 86 33.180 0.38582</code></pre>
<pre class="r"><code>###post-hoc t 
combine%&gt;%group_by(Tumor_Sample_Type)%&gt;%summarize(mean(H2AFX),mean(Genome_Altered),mean(Mutation_Count))</code></pre>
<pre><code>## # A tibble: 4 x 4
## Tumor_Sample_Type `mean(H2AFX)` `mean(Genome_Altered)`
`mean(Mutation_Count)`
## &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 breast_Metastasis 0.175 0.548 423.
## 2 breast_Primary -0.399 0.667 428
## 3 colorectal_Metastasis 0.238 0.423 848.
## 4 colorectal_Primary 0.222 0.382 2295.</code></pre>
<pre class="r"><code>pairwise.t.test(combine$H2AFX, combine$Tumor_Sample_Type, p.adj=&quot;none&quot;)</code></pre>
<pre><code>##
## Pairwise comparisons using t tests with pooled SD
##
## data: combine$H2AFX and combine$Tumor_Sample_Type
##
## breast_Metastasis breast_Primary colorectal_Metastasis
## breast_Primary 0.0209 - -
## colorectal_Metastasis 0.8499 0.0619 -
## colorectal_Primary 0.8378 0.0096 0.9605
##
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(combine$Genome_Altered, combine$Tumor_Sample_Type, p.adj=&quot;none&quot;)</code></pre>
<pre><code>##
## Pairwise comparisons using t tests with pooled SD
##
## data: combine$Genome_Altered and
combine$Tumor_Sample_Type
##
## breast_Metastasis breast_Primary colorectal_Metastasis
## breast_Primary 0.0528 - -
## colorectal_Metastasis 0.1361 0.0046 -
## colorectal_Primary 0.0046 4.6e-06 0.6123
##
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(combine$Mutation_Count, combine$Tumor_Sample_Type, p.adj=&quot;none&quot;)</code></pre>
<pre><code>##
## Pairwise comparisons using t tests with pooled SD
##
## data: combine$Mutation_Count and
combine$Tumor_Sample_Type
##
## breast_Metastasis breast_Primary colorectal_Metastasis
## breast_Primary 0.9940 - -
## colorectal_Metastasis 0.6374 0.6448 -
## colorectal_Primary 0.0032 0.0040 0.1034
##
## P value adjustment method: none</code></pre>
<p>The overall MANOVA is significant (p=0.00293), then I did a one-way ANOVAs for each variable, and found Genome_Altered , Mutation_Count and H2AFX are significant.</p>
<p>I have done 1 MANOVA and 7 anovas,and 18 (3 different variables in 4 groups) t-test, total 26 tests. The type I error rate is .05/26=0.001923077. Based on this value, expression level of H2AFX for primary site is significant between colorectal and breast cancer. Genome_Altered is significant for primary sites, metastasis and primary sites between colorectal and breast cancer. Mutation_Count for primary site is significant between colorectal and breast cancer, and is also significant between colorectal_Primary vs. breast_Metastasis.</p>
<p>Since breast cancer and colorectal cancer are different cancer type, their genomic alteration might also be different. And I also found Genome_Altered and Mutation_Count are significant different for primary sites between colorectal and breast cancer.</p>
<ul>
<li><strong>2. (10 pts)</strong> Perform some kind of randomization test on your data (that makes sense). The statistic can be anything you want (mean difference, correlation, F-statistic/ANOVA, chi-squared), etc. State null and alternative hypotheses, perform the test, and interpret the results (7). Create a plot visualizing the null distribution and the test statistic (3).</li>
</ul>
<pre class="r"><code>combine_2 &lt;- left_join(clinical, mRNA, by=c(&quot;Sample_ID&quot;=&quot;SAMPLE_ID&quot;)) %&gt;% filter(Tumor_Type==&quot;breast&quot;) %&gt;% na.omit() %&gt;% select(Sample_Type, H2AFX)
combine_2 %&gt;% group_by(Sample_Type) %&gt;% summarise(means=mean(H2AFX)) %&gt;% summarise(diff(means))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   `diff(means)`
##           &lt;dbl&gt;
## 1        -0.574</code></pre>
<pre class="r"><code>rand_dist&lt;-vector()
for(i in 1:5000){ 
  new&lt;-data.frame(Sample_Type=sample(combine_2$Sample_Type),H2AFX=combine_2$H2AFX) 
  rand_dist[i]&lt;-mean(new[new$Sample_Type==&quot;Primary&quot;,]$H2AFX)-
  mean(new[new$Sample_Type==&quot;Metastasis&quot;,]$H2AFX)}
mean(rand_dist&gt;0.5737567 | rand_dist &lt; -0.5737567)</code></pre>
<pre><code>## [1] 0.033</code></pre>
<pre class="r"><code>hist(rand_dist,main=&quot;&quot;,ylab=&quot;&quot;)
abline(v = c(-0.5737567, 0.5737567),col=&quot;red&quot;)</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-3-1.png" width="768" style="display: block; margin: auto;" />
My project will mainly focus on the function of DNA damage response gene H2AFX in breast cancer primary sites and breast cancer metastasis sites. So I selected breast cancer and H2AFX expression level to explore if it is significant between primary and metastasis sites in breast cancer. My null hypothesis is there is no difference between primary and metastasis sites. I performed 5000 times randomization of my data and explored distribution. I found the p-value is 0.036, then I rejected the null hypothesis.</p>
<ul>
<li><p><strong>3. (40 pts)</strong> Build a linear regression model predicting one of your response variables from at least 2 other variables, including their interaction. Mean-center any numeric variables involved in the interaction.</p>
<ul>
<li>Interpret the coefficient estimates (do not discuss significance) (10)</li>
<li>Plot the regression using <code>ggplot()</code> using geom_smooth(method=“lm”). If your interaction is numeric by numeric, refer to code in the slides to make the plot or check out the <code>interactions</code> package, which makes this easier. If you have 3 or more predictors, just chose two of them to plot for convenience. (10)</li>
<li>What proportion of the variation in the outcome does your model explain? (4)</li>
<li>Check assumptions of linearity, normality, and homoskedasticity either graphically or using a hypothesis test (5)</li>
<li>Regardless, recompute regression results with robust standard errors via <code>coeftest(..., vcov=vcovHC(...))</code>. Discuss significance of results, including any changes from before/after robust SEs if applicable. (10)</li>
</ul></li>
</ul>
<pre class="r"><code>library(lmtest)
library(sandwich)
combine_3 &lt;- left_join(clinical, mRNA, by=c(&quot;Sample_ID&quot;=&quot;SAMPLE_ID&quot;)) %&gt;% filter(Tumor_Type==&quot;colorectal&quot;) %&gt;% na.omit() 
combine_3_c &lt;- combine_3 %&gt;% mutate(Genome_Altered_c=Genome_Altered-mean(Genome_Altered)) %&gt;% mutate(Mutation_Count_c=Mutation_Count-mean(Mutation_Count)) %&gt;% mutate(H2AFX_c=H2AFX-mean(H2AFX))
#combine_3_c$Sample_Type&lt;-relevel(combine_3_c$Sample_Type,ref=&quot;Primary&quot;)
fit&lt;-lm(Genome_Altered_c ~ Mutation_Count_c*Sample_Type, data=combine_3_c); summary(fit)</code></pre>
<pre><code>##
## Call:
## lm(formula = Genome_Altered_c ~ Mutation_Count_c *
Sample_Type,
## data = combine_3_c)
##
## Residuals:
## Min 1Q Median 3Q Max
## -0.35658 -0.11330 -0.01902 0.10785 0.47156
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) -1.653e-01 1.082e-01 -1.527 0.1355
## Mutation_Count_c -1.759e-04 7.604e-05 -2.314 0.0265 *
## Sample_TypePrimary 1.689e-01 1.141e-01 1.481 0.1473
## Mutation_Count_c:Sample_TypePrimary 1.361e-04 7.662e-05
1.776 0.0842 .
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 0.1999 on 36 degrees of freedom
## Multiple R-squared: 0.3957, Adjusted R-squared: 0.3453
## F-statistic: 7.858 on 3 and 36 DF, p-value: 0.0003688</code></pre>
<pre class="r"><code>combine_3_c %&gt;% ggplot(aes(Genome_Altered_c,Mutation_Count_c,group=Sample_Type)) + geom_point(aes(color=Sample_Type)) +geom_smooth(aes(color=Sample_Type),method=&quot;lm&quot;)</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-4-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>###Check assumptions of linearity, normality, and homoskedasticity either graphically or using a hypothesis test 
resids&lt;-fit$residuals
fitvals&lt;-fit$fitted.values
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, color=&#39;red&#39;)</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-4-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ks.test(resids, &quot;pnorm&quot;, mean=0, sd(resids))</code></pre>
<pre><code>## 
##  One-sample Kolmogorov-Smirnov test
## 
## data:  resids
## D = 0.086168, p-value = 0.903
## alternative hypothesis: two-sided</code></pre>
<pre class="r"><code>shapiro.test(resids)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  resids
## W = 0.98264, p-value = 0.7861</code></pre>
<pre class="r"><code>coeftest(fit)</code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) -1.6527e-01 1.0823e-01 -1.5271 0.13549
## Mutation_Count_c -1.7592e-04 7.6038e-05 -2.3136 0.02651
*
## Sample_TypePrimary 1.6894e-01 1.1407e-01 1.4810 0.14730
## Mutation_Count_c:Sample_TypePrimary 1.3609e-04
7.6618e-05 1.7762 0.08416 .
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>coeftest(fit, vcov=vcovHC(fit))</code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) -1.6527e-01 3.4510e-02 -4.7891 2.857e-05 ***
## Mutation_Count_c -1.7592e-04 2.6679e-05 -6.5940
1.126e-07 ***
## Sample_TypePrimary 1.6894e-01 5.5462e-02 3.0460 0.004322
**
## Mutation_Count_c:Sample_TypePrimary 1.3609e-04
4.7117e-05 2.8883 0.006518 **
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<p>I tried to explore relationship among all the variables with Genome_Altered in colorectal cancer. Mean/predicted Genome_Altered_c for primary site with average Mutation_Count is 3.665e-03. Mutation_Count significantly associated with Genome_Altered_c for primary site: for every 1-unit increase in Mutation_Count, predicted Genome_Altered_c decreased 3.983e-05 for this group. Metastasis with average Mutation_Count have predicted Genome_Altered_c that is 1.689e-01 lower than primary sites with average Mutation_Count. Slope of Mutation_Count on Genome_Altered_c for Metastasis is 1.361e-04 lower than primary sites.</p>
<p>The R-square is 0.3453, so my model could explain 34.53% of the variation in the outcome.</p>
<p>With both Kolmogorov-Smirnov and Shapiro-Wilk, I failed to reject, hence the normality is fine.</p>
<p>With the robust standard errors, Metastasis with average Mutation_Count have predicted Genome_Altered_c that is 1.6894e-01 lower than primary sites with average Mutation_Count(significant). Slope of Mutation_Count on Genome_Altered_c for Metastasis is 1.3609e-04 lower than primary sites (significant). However, Mutation_Count is not significantly associated with Genome_Altered_c for primary site.</p>
<ul>
<li><strong>4. (5 pts)</strong> Rerun same regression model (with the interaction), but this time compute bootstrapped standard errors (either by resampling observations or residuals). Discuss any changes you observe in SEs and p-values using these SEs compared to the original SEs and the robust SEs)</li>
</ul>
<pre class="r"><code>combine_4 &lt;- combine_3_c %&gt;% select(Genome_Altered_c, Mutation_Count_c, Sample_Type)
samp_distn&lt;-replicate(5000, { 
  combine_4_p &lt;- combine_4[combine_4$Sample_Type==&quot;Primary&quot;,]
  combine_4_m &lt;- combine_4[combine_4$Sample_Type==&quot;Metastasis&quot;,]
  boot_dat_p&lt;-combine_4_p[sample(nrow(combine_4_p),replace=TRUE),] 
  boot_dat_m&lt;-combine_4_m[sample(nrow(combine_4_m),replace=TRUE),] 
  boot_dat &lt;- merge(boot_dat_p,boot_dat_m, all=T)
  fit&lt;-lm(Genome_Altered_c ~ Mutation_Count_c*Sample_Type, data=boot_dat)
coef(fit)
})
samp_distn%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>## (Intercept) Mutation_Count_c Sample_TypePrimary
Mutation_Count_c:Sample_TypePrimary
## 1 0.3299405 0.0002086913 0.3319256 0.0002104406</code></pre>
<pre class="r"><code>samp_distn%&gt;%t%&gt;%as.data.frame%&gt;%gather%&gt;%group_by(key)%&gt;% summarize(lower=quantile(value,.025), upper=quantile(value,.975))</code></pre>
<pre><code>## # A tibble: 4 x 3
## key lower upper
## &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 (Intercept) -1.35 -0.123
## 2 Mutation_Count_c -0.000909 -0.000130
## 3 Mutation_Count_c:Sample_TypePrimary 0.0000464 0.000860
## 4 Sample_TypePrimary 0.0648 1.34</code></pre>
<p>With bootstrapped standard errors, none of my variables is significant. Since the standard errors are too big for them to be significant.</p>
<ul>
<li><p><strong>5. (30 pts)</strong> Fit a logistic regression model predicting a binary variable (if you don’t have one, make/get one) from at least two explanatory variables (interaction not necessary).</p>
<ul>
<li>Interpret coefficient estimates in context (10)</li>
<li>Report a confusion matrix for your logistic regression (5)</li>
<li>Compute and discuss the Accuracy, Sensitivity (TPR), Specificity (TNR), Precision (PPV), and AUC of your model (5)</li>
<li>Using ggplot, make a density plot of the log-odds (logit) colored/grouped by your binary outcome variable (5)</li>
<li>Generate an ROC curve (plot) and calculate AUC (either manually or with a package); interpret (5)</li>
</ul></li>
</ul>
<pre class="r"><code>combine_5 &lt;- left_join(clinical, mRNA, by=c(&quot;Sample_ID&quot;=&quot;SAMPLE_ID&quot;)) %&gt;% filter(Tumor_Type==&quot;breast&quot;) %&gt;% na.omit()
data&lt;-combine_5 %&gt;%mutate(y=ifelse(Sample_Type==&quot;Metastasis&quot;,1,0))
fit&lt;-glm(y~H2AFX+Mutation_Count+Genome_Altered,data=data,family=&quot;binomial&quot;)
coeftest(fit)</code></pre>
<pre><code>##
## z test of coefficients:
##
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) 2.66351038 1.31159305 2.0307 0.04228 *
## H2AFX 0.65645350 0.34692576 1.8922 0.05846 .
## Mutation_Count -0.00032663 0.00090304 -0.3617 0.71758
## Genome_Altered -3.87198441 1.91152775 -2.0256 0.04281 *
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>exp(coef(fit))</code></pre>
<pre><code>## (Intercept) H2AFX Mutation_Count Genome_Altered
## 14.34656265 1.92794275 0.99967342 0.02081702</code></pre>
<pre class="r"><code>data$predicted &lt;- predict(fit, type = &quot;response&quot;)
table(predict=as.numeric(data$predicted&gt;.5),truth=data$y)%&gt;%addmargins</code></pre>
<pre><code>##        truth
## predict  0  1 Sum
##     0   15  8  23
##     1    9 18  27
##     Sum 24 26  50</code></pre>
<pre class="r"><code>#sensitivity
mean(data[data$y==1,]$predicted&gt;.5)</code></pre>
<pre><code>## [1] 0.6923077</code></pre>
<pre class="r"><code>#specificity
mean(data[data$y==0,]$predicted&lt;.5)</code></pre>
<pre><code>## [1] 0.625</code></pre>
<pre class="r"><code>#Precision
18/27</code></pre>
<pre><code>## [1] 0.6666667</code></pre>
<pre class="r"><code>data$logit&lt;-predict(fit,  type= &quot;link&quot;)
ggplot(data, aes(x=logit,fill=Sample_Type))+geom_density(alpha = 0.5)</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-6-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>library(plotROC)
ROCplot&lt;-ggplot(data)+geom_roc(aes(d=y,m=predicted), n.cuts=0); ROCplot</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-6-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.7323718</code></pre>
<p>For breast cancer, log-odds for primary site is 2.66351038, odds is 14.34656265. Log-odds for metastasis site is 2.66351038+0.65645350-0.00032663-3.87198441=-0.5523472, odds is 0.5755972.</p>
<p>Sensitivity is 0.6923077, specificity is 0.625 and precision is 0.6666667. The AUC is 0.7323718.</p>
<ul>
<li><p><strong>6. (25 pts)</strong> Perform a logistic regression predicting the same binary response variable from <em>ALL</em> of the rest of your variables (the more, the better!)</p>
<ul>
<li>Fit model, compute in-sample classification diagnostics (Accuracy, Sensitivity, Specificity, Precision, AUC), and interpret (5)</li>
<li>Perform 10-fold (or repeated random sub-sampling) CV with the same model and report average out-of-sample classification diagnostics (Accuracy, Sensitivity, Specificity, Precision, and AUC); interpret AUC and compare with the in-sample metrics (10)</li>
<li>Perform LASSO on the same model/variables. Choose lambda to give the simplest model whose accuracy is near that of the best (i.e., <code>lambda.1se</code>). Discuss which variables are retained. (5)</li>
<li>Perform 10-fold CV using only the variables lasso selected: compare model’s out-of-sample AUC to that of your logistic regressions above (5)</li>
</ul></li>
</ul>
<pre class="r"><code>class_diag&lt;-function(probs,truth){
  
  tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2]
  spec=tab[1,1]/colSums(tab)[1]
  ppv=tab[2,2]/rowSums(tab)[2]
  
  if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
  
  #CALCULATE EXACT AUC
  ord&lt;-order(probs, decreasing=TRUE)
  probs &lt;- probs[ord]; truth &lt;- truth[ord]
  
  TPR=cumsum(truth)/max(1,sum(truth)) 
  FPR=cumsum(!truth)/max(1,sum(!truth))
  
  dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
  TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
  
  n &lt;- length(TPR)
  auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )
  
  data.frame(acc,sens,spec,ppv,auc)
}


combine_6 &lt;- left_join(clinical, mRNA, by=c(&quot;Sample_ID&quot;=&quot;SAMPLE_ID&quot;)) %&gt;% filter(Tumor_Type==&quot;breast&quot;) %&gt;% na.omit()
data6&lt;-combine_6 %&gt;%mutate(y=ifelse(Sample_Type==&quot;Metastasis&quot;,1,0))
data_fin&lt;-data6 %&gt;% select(-Sample_ID,-STUDY_ID,-Tumor_Type,-Sample_Type)
fit&lt;-glm(y~.,data=data_fin,family=&quot;binomial&quot;)
coeftest(fit)</code></pre>
<pre><code>##
## z test of coefficients:
##
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) 3.21574405 1.85378686 1.7347 0.08280 .
## Age -0.01004096 0.02569401 -0.3908 0.69595
## Genome_Altered -4.32594122 2.06712119 -2.0927 0.03637 *
## Mutation_Count -0.00021952 0.00095053 -0.2309 0.81736
## HK2 -0.06756819 0.34814073 -0.1941 0.84611
## KEAP1 -0.09160619 0.29971827 -0.3056 0.75988
## H2AFX 0.68096365 0.36340618 1.8738 0.06095 .
## TP63 -0.79063942 0.61600872 -1.2835 0.19932
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>exp(coef(fit))</code></pre>
<pre><code>## (Intercept) Age Genome_Altered Mutation_Count HK2 KEAP1
## 24.9218281 0.9900093 0.0132211 0.9997805 0.9346640
0.9124644
## H2AFX TP63
## 1.9757808 0.4535547</code></pre>
<pre class="r"><code>data_fin$predicted &lt;- predict(fit, type = &quot;response&quot;)
table(predict=as.numeric(data_fin$predicted&gt;.5),truth=data_fin$y)%&gt;%addmargins</code></pre>
<pre><code>##        truth
## predict  0  1 Sum
##     0   16  7  23
##     1    8 19  27
##     Sum 24 26  50</code></pre>
<pre class="r"><code>#sensitivity
mean(data_fin[data_fin$y==1,]$predicted&gt;.5)</code></pre>
<pre><code>## [1] 0.7307692</code></pre>
<pre class="r"><code>#specificity
mean(data_fin[data_fin$y==0,]$predicted&lt;.5)</code></pre>
<pre><code>## [1] 0.6666667</code></pre>
<pre class="r"><code>#Precision
19/27</code></pre>
<pre><code>## [1] 0.7037037</code></pre>
<pre class="r"><code>#Accuracy
(16+19)/50</code></pre>
<pre><code>## [1] 0.7</code></pre>
<pre class="r"><code>#AUC
library(plotROC)
ROCplot&lt;-ggplot(data_fin)+geom_roc(aes(d=y,m=predicted), n.cuts=0); ROCplot</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-7-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.7772436</code></pre>
<pre class="r"><code>#10-fold 
set.seed(1234)
k=10
data_fold &lt;- data_fin %&gt;% sample_frac
folds &lt;- ntile(1:nrow(data_fold),n=10)
diags&lt;-NULL
for(i in 1:k){
  train &lt;- data_fold[folds!=i,]
  test &lt;- data_fold[folds==i,]
  truth &lt;- test$y
  fit &lt;- glm(y~., data=train, family=&quot;binomial&quot;)
  probs &lt;- predict(fit, newdata=test, type=&quot;response&quot;)
  
  diags&lt;-rbind(diags,class_diag(probs,truth))
}
mean(diags$acc)</code></pre>
<pre><code>## [1] 0.58</code></pre>
<pre class="r"><code>mean(diags$sens)</code></pre>
<pre><code>## [1] 0.55</code></pre>
<pre class="r"><code>mean(diags$spec)</code></pre>
<pre><code>## [1] 0.4666667</code></pre>
<pre class="r"><code>mean(diags$ppv)</code></pre>
<pre><code>## [1] NaN</code></pre>
<pre class="r"><code>mean(diags$auc)</code></pre>
<pre><code>## [1] 0.4083333</code></pre>
<pre class="r"><code>###LASSO
data_lasso&lt;-data6 %&gt;% select(-Sample_ID,-STUDY_ID,-Tumor_Type,-y)
library(glmnet)
y&lt;-as.matrix(data_lasso$Sample_Type)
x&lt;-model.matrix(Sample_Type~.,data=data_lasso)[,-1] 
cv&lt;-cv.glmnet(x,y,family=&quot;binomial&quot;)
cv&lt;-cv.glmnet(x,y,family=&quot;binomial&quot;)
plot(cv$glmnet.fit,&quot;lambda&quot;,labe=TRUE); abline(v = log(cv$lambda.1se)); abline(v = log(cv$lambda.min),lty=2)</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-7-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>lasso&lt;-glmnet(x,y,family=&quot;binomial&quot;,lambda=cv$lambda.1se)
coef(lasso)</code></pre>
<pre><code>## 8 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                           s0
## (Intercept)    -8.004271e-02
## Age             .           
## Genome_Altered  5.896281e-16
## Mutation_Count  .           
## HK2             .           
## KEAP1           .           
## H2AFX           .           
## TP63            .</code></pre>
<pre class="r"><code>#10-fold with new 
combine_6 &lt;- left_join(clinical, mRNA, by=c(&quot;Sample_ID&quot;=&quot;SAMPLE_ID&quot;)) %&gt;% filter(Tumor_Type==&quot;breast&quot;) %&gt;% na.omit()
data6&lt;-combine_6 %&gt;%mutate(y=ifelse(Sample_Type==&quot;Metastasis&quot;,1,0))
set.seed(1234)
k=10
data_fold_lasso &lt;- data6 %&gt;% sample_frac
folds &lt;- ntile(1:nrow(data_fold_lasso),n=10)
diags&lt;-NULL
for(i in 1:k){
  train &lt;- data_fold_lasso[folds!=i,]
  test &lt;- data_fold_lasso[folds==i,]
  truth &lt;- test$y
  fit &lt;- glm(y~Genome_Altered, data=train, family=&quot;binomial&quot;)
  probs &lt;- predict(fit, newdata=test, type=&quot;response&quot;)
  
  diags&lt;-rbind(diags,class_diag(probs,truth))
}
mean(diags$auc)</code></pre>
<pre><code>## [1] 0.6666667</code></pre>
<p>Sensitivity is 0.7307692, specificity is 0.6666667 ,precision is 0.7037037 and the accuracy is 0.7. The AUC is 0.7772436.</p>
<p>After 10-fold the sensitivity is 0.6083333, specificity is 0.525 ,precision is 0.5216667 and the accuracy is 0.56. The AUC is 0.5083333. Which indicated my data is overfitting.</p>
<p>With LASSO I will keep Genome_Altered.</p>
<p>With the new variable, my 10-fold auc is 0.6666667.
## Where do I find data again?</p>
<p>You can choose ANY datasets you want that meet the above criteria for variables and observations. You can make it as serious as you want, or not, but keep in mind that you will be incorporating this project into a portfolio webpage for your final in this course, so choose something that really reflects who you are, or something that you feel will advance you in the direction you hope to move career-wise, or something that you think is really neat, or whatever. On the flip side, regardless of what you pick, you will be performing all the same tasks, so it doesn’t end up being that big of a deal.</p>
<p>If you are totally clueless and have no direction at all, log into the server and type</p>
<pre class="r"><code>data(package = .packages(all.available = TRUE))</code></pre>
<p>This will print out a list of <strong>ALL datasets in ALL packages</strong> installed on the server (a ton)! Scroll until your eyes bleed! Actually, do not scroll that much… To start with something more manageable, just run the command on your own computer, or just run <code>data()</code> to bring up the datasets in your current environment. To read more about a dataset, do <code>?packagename::datasetname</code>.</p>
<p>If it is easier for you, and in case you don’t have many packages installed, a list of R datasets from a few common packages (also downloadable in CSV format) is given at the following website: <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a>.</p>
<ul>
<li><p>A good package to download for fun/relevant data is <code>fivethiryeight</code>.
Run <code>install.packages("fivethirtyeight"),</code> load the packages with <code>library(fivethirtyeight)</code>, run <code>data()</code>, and then scroll down to view the datasets. Here is an online list of all 127 datasets (with links to the 538 articles). Lots of sports, politics, current events, etc.</p></li>
<li><p>If you have already started to specialize (e.g., ecology, epidemiology) you might look at discipline-specific R packages (vegan, epi, respectively). We will be using some tools from these packages later in the course, but they come with lots of data too, which you can explore according to the directions above</p></li>
<li><p>However, you <em>emphatically DO NOT</em> have to use datasets available via R packages! In fact, I would much prefer it if you found the data from completely separate sources and brought them together (a much more realistic experience in the real world)! You can even reuse data from your SDS328M project, provided it shares a variable in common with other data which allows you to merge the two together (e.g., if you still had the timestamp, you could look up the weather that day: <a href="https://www.wunderground.com/history/" class="uri">https://www.wunderground.com/history/</a>). If you work in a research lab or have access to old data, you could potentially merge it with new data from your lab!</p></li>
<li><p>Here is a curated list of interesting datasets (read-only spreadsheet format): <a href="https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit" class="uri">https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit</a></p></li>
<li><p>Here is another great compilation of datasets: <a href="https://github.com/rfordatascience/tidytuesday" class="uri">https://github.com/rfordatascience/tidytuesday</a></p></li>
<li><p>Here is the UCI Machine Learning Repository: <a href="https://archive.ics.uci.edu/ml/index.php" class="uri">https://archive.ics.uci.edu/ml/index.php</a></p>
<ul>
<li>See also <a href="https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data" class="uri">https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data</a></li>
</ul></li>
<li><p>Here is another good general place to look: <a href="https://www.kaggle.com/datasets" class="uri">https://www.kaggle.com/datasets</a></p></li>
<li><p>To help narrow your search down or to see interesting variable ideas, check out <a href="https://www.tylervigen.com/spurious-correlations" class="uri">https://www.tylervigen.com/spurious-correlations</a>. This is the spurious correlations website, and it is fun, but if you look at the bottom of each plot you will see sources for the data. This is a good place to find very general data (or at least get a sense of where you can scrape data together from)!</p></li>
<li><p>If you are interested in medical data, check out www.countyhealthrankings.org</p></li>
<li><p>If you are interested in scraping UT data, they make <em>loads</em> of data public (e.g., beyond just professor CVs and syllabi). Check out all the data that is available in the statistical handbooks: <a href="https://reports.utexas.edu/statistical-handbook" class="uri">https://reports.utexas.edu/statistical-handbook</a></p></li>
</ul>
<div id="broader-data-sources" class="section level5">
<h5>Broader data sources:</h5>
<p><a href="www.data.gov">Data.gov</a> 186,000+ datasets!</p>
<p><a href="Social%20Explorer">Social Explorer</a> is a nice interface to Census and American Community Survey data (more user-friendly than the government sites). May need to sign up for a free trial.</p>
<p><a href="www.bls.gov">U.S. Bureau of Labor Statistics</a></p>
<p><a href="www.census.gov">U.S. Census Bureau</a></p>
<p><a href="www.gapminder.org/data">Gapminder</a>, data about the world.</p>
<p>…</p>
</div>
</div>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/js/docs.min.js"></script>
<script src="/js/main.js"></script>

<script src="/js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
